### ISSUE TITLE
Add better conditional functionality

### ISSUE THREAD

**Issue by nebrelbug** [nebrelbug/squirrelly#1]
Make it so that conditionals & options can be nested inside conditionals.

**Comment by iamw00t** [comment]
Was this updated to support nested conditionals? If so can you provide me an example please, I can't seem to do it

**Comment by nebrelbug** [comment]
Hi @iamw00t, thanks for the question! Nested conditionals do now work. Example:

https://runkit.com/nebrelbug/squirrelly-nested-conditionals

Let me know if this solves your problem!
