### ISSUE TITLE
undefined ... 

### ISSUE THREAD

**Issue by Indribell** [nebrelbug/squirrelly#104]
When having a tag in the code:

```
let myTemplate = `This is a template
My favorite template engine is: {{fav}}
My favorite kind of cake is: {{cake}}
Not used {{cakerrrsr}}
`;
 let templateResult = Sqrl.Render(myTemplate, {
        fav: "Squirrelly", cake: "Chocolate",
    });
```

```
This is a template
My favorite template engine is: Squirrelly
My favorite kind of cake is: Chocolate
Not used undefined
```

The "cakerrrsr" that has no matching data in a json, results in "undefined" being printed onscreen. It may be better to not display anything, like Handlebars and co do.

**Comment by nebrelbug** [comment]
Hi @Indribell! I've been thinking about this, and I think that including an option to enable this behavior might be a nice feature for version 8! If you would like to see this, please comment on the version 8 issue I created.

Thanks!

**Comment by ilanl** [comment]
love to see this
