### ISSUE TITLE
Conditionals inside loop with use of variable loop

### ISSUE THREAD

**Issue by florent1933** [nebrelbug/squirrelly#110]
I am using squirrelly  as a templating engine for nodeJS.

I didn't succeed to use conditionals with the variable from the loop.

```
{{each(options.pixels)}}
  
  {{if(this.platform === 'facebook')}}
    {{@this.value}}
  {{/if}}
{{/each}}
```

Is it possible?

**Comment by nebrelbug** [comment]
Hi @florent1933, thanks for the question!

You just need to change `this.platform` to `@this.platform`.

```
{{each(options.pixels)}}
  
  {{if(@this.platform === 'facebook')}}
    {{@this.value}}
  {{/if}}
{{/each}}
```

I'm glad to hear that you're using Squirrelly! Feel free to ask any more questions you might have :+1:

**Comment by nebrelbug** [comment]
Let me know if this solves your problem.

**Comment by florent1933** [comment]
It's working like a charm. Thanks @nebrelbug 🥇

**Comment by nebrelbug** [comment]
@florent1933 great! If you have any more questions, don't hesitate to contact me 😃
