### ISSUE TITLE
Does Squirrelly support conditional operators?

### ISSUE THREAD

**Issue by pbrianmackey** [nebrelbug/squirrelly#112]
Is there support for this kind of logic:

```
{{if(options.somevalue === 1 && options.someothervalue === 1)}}
Display this
{{#else}}
Display this
{{/if}}
```

Handlebarsjs was my first try and it doesn't support it natively.  I read through the documentation and could not find the answer to this.

**Comment by nebrelbug** [comment]
Hi @pbrianmackey, thanks for the question! There is support for conditionals, and they have exactly the syntax that you wrote down.

Here's an example:
https://runkit.com/nebrelbug/squirrelly-with-conditionals
