### ISSUE TITLE
Remove alt text from Github Images

### ISSUE THREAD

**Issue by nebrelbug** [nebrelbug/squirrelly#3]
The alt text from the github fork/star/etc. images is showing up with the NPM package search description, so the alt text needs to be removed.

**Comment by psycho5** [comment]
@nebrelbug Could I call dips on this one!

**Comment by nebrelbug** [comment]
Sure! Thanks for helping! I'm sorry I didn't respond sooner.

**Comment by nebrelbug** [comment]
Closed by PR #8. Thanks @psycho5 !
